#Matthew Umana msu245 Assignment 2

import math
import turtle

radius = eval(input("Enter the length from the center to a vertex: "))
side = (2 * radius) * math.sin(math.pi/5)
area = ((3 * math.sqrt(3)) / 2) * side**2
print("The area of the pentagon is", round(area, 2))


name = input("Enter employee’s name: ")
hours = eval(input("Enter number of hours worked this week: "))
rate = eval(input("Enter hourly pay rate: "))
f_tax_withold = eval(input("Enter federal tax withholding rate (%): "))
s_tax_withold = eval(input("Enter state tax withholding rate (%): "))
gross_pay = (hours * rate)

rate_string = "$" + str(format(rate, ".2f")) 
gross_pay_string = "$" + str(format(gross_pay, ".2f"))
f_tax_withold_string = "$" + str(format((gross_pay * (f_tax_withold / 100)), ".2f"))
s_tax_withold_string = "$" + str(format((gross_pay * (s_tax_withold / 100)), ".2f"))
f_tax_withold_string2 = "  Federal Withholding ({}):".format((str(f_tax_withold) + "%"))
s_tax_withold_string2 = "  State Withholding ({}):".format((str(s_tax_withold) + "%"))
net_pay = format(gross_pay - ((gross_pay * (f_tax_withold / 100)) + (gross_pay * (s_tax_withold/ 100))), ".2f")

print("Weekly Pay Statement for", name)
print("Hours Worked:", format(hours, "8.1f"))
print(format("Pay Rate:", "<9") + format(rate_string, ">13"))
print(format("Gross Pay:", "<10") + format(gross_pay_string, ">12"))
print("Deductions:")

print(format(f_tax_withold_string2, "<26") + format(f_tax_withold_string, ">8"))
print(format(s_tax_withold_string2, "<25") + format(s_tax_withold_string, ">9"))
print("Net Pay: " + "$" + str(net_pay))

turtle.speed(0)
turtle.penup()
turtle.goto(-140,-150)
turtle.pendown()
turtle.fillcolor('grey')
turtle.begin_fill()
turtle.setheading(-45)
turtle.circle(200,90)
turtle.circle(100,90)
turtle.circle(200,90)
turtle.circle(100,90)
turtle.end_fill()
turtle.penup()
turtle.goto(-200,-90)
turtle.pendown()
turtle.fillcolor('white')
turtle.begin_fill()
turtle.circle(40, 360)
turtle.end_fill()
turtle.penup()
turtle.goto(125,-30)
turtle.pendown()
turtle.fillcolor('grey')
turtle.begin_fill()
turtle.circle(150,90)
turtle.circle(75,90)
turtle.circle(150,90)
turtle.circle(75,90)
turtle.end_fill()
turtle.penup()
turtle.goto(200,75)
turtle.pendown()
turtle.fillcolor('grey')
turtle.begin_fill()
turtle.circle(5,90)
turtle.circle(200,90)
turtle.circle(5,90)
turtle.circle(200,90)
turtle.end_fill()
turtle.penup()
turtle.goto(-205,-200)
turtle.pendown()
turtle.fillcolor('white')
turtle.begin_fill()
turtle.circle(150,90)
turtle.circle(20,90)
turtle.circle(150,90)
turtle.circle(20,90)
turtle.end_fill()
turtle.penup()
turtle.goto(50,-200)
turtle.pendown()
turtle.fillcolor('white')
turtle.begin_fill()
turtle.circle(150,90)
turtle.circle(20,90)
turtle.circle(150,90)
turtle.circle(20,90)
turtle.end_fill()
turtle.pendown()
turtle.penup()
turtle.goto(250,60)
turtle.fillcolor('black')
turtle.begin_fill()
turtle.circle(20,90)
turtle.circle(20,90)
turtle.circle(20,90)
turtle.circle(20,90)
turtle.end_fill()
turtle.penup()

ts = turtle.getscreen()
ts.getcanvas().postscript(file='Umana_Matthew.eps')






